### ISSUE TITLE
Build email to share Question/Quest as a graph

### ISSUE THREAD

**Issue by playdough** [playdough/quest#6]

**Comment by playdough** [comment]
Use a line graph

**Comment by PaDoMeNe** [comment]
Each graph would include 2 lines: 1 for projections; the other for actual. The graph would be titled with the Quest and Question (probably on separate lines.) The vertical (i.e. y) axis references the numbers 1-10. The horizontal (i.e. x) axis references the dates. In a perfect world, the lines would be contrasting colors with a legend at the bottom identifying "Projected" & "Experienced/Actual" (or something like that)

**Comment by playdough** [comment]
give that a try.
